// Code generated by MockGen. DO NOT EDIT.
// Source: ports/query_validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQueryValidatorPort is a mock of QueryValidatorPort interface.
type MockQueryValidatorPort struct {
	ctrl     *gomock.Controller
	recorder *MockQueryValidatorPortMockRecorder
}

// MockQueryValidatorPortMockRecorder is the mock recorder for MockQueryValidatorPort.
type MockQueryValidatorPortMockRecorder struct {
	mock *MockQueryValidatorPort
}

// NewMockQueryValidatorPort creates a new mock instance.
func NewMockQueryValidatorPort(ctrl *gomock.Controller) *MockQueryValidatorPort {
	mock := &MockQueryValidatorPort{ctrl: ctrl}
	mock.recorder = &MockQueryValidatorPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryValidatorPort) EXPECT() *MockQueryValidatorPortMockRecorder {
	return m.recorder
}

// ContainsDDLDML mocks base method.
func (m *MockQueryValidatorPort) ContainsDDLDML(query string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsDDLDML", query)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsDDLDML indicates an expected call of ContainsDDLDML.
func (mr *MockQueryValidatorPortMockRecorder) ContainsDDLDML(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsDDLDML", reflect.TypeOf((*MockQueryValidatorPort)(nil).ContainsDDLDML), query)
}

// IsSafe mocks base method.
func (m *MockQueryValidatorPort) IsSafe(query string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSafe", query)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSafe indicates an expected call of IsSafe.
func (mr *MockQueryValidatorPortMockRecorder) IsSafe(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSafe", reflect.TypeOf((*MockQueryValidatorPort)(nil).IsSafe), query)
}
