// Code generated by MockGen. DO NOT EDIT.
// Source: ports/hash.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockHashPort is a mock of HashPort interface.
type MockHashPort struct {
	ctrl     *gomock.Controller
	recorder *MockHashPortMockRecorder
}

// MockHashPortMockRecorder is the mock recorder for MockHashPort.
type MockHashPortMockRecorder struct {
	mock *MockHashPort
}

// NewMockHashPort creates a new mock instance.
func NewMockHashPort(ctrl *gomock.Controller) *MockHashPort {
	mock := &MockHashPort{ctrl: ctrl}
	mock.recorder = &MockHashPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashPort) EXPECT() *MockHashPortMockRecorder {
	return m.recorder
}

// GenerateChecksum mocks base method.
func (m *MockHashPort) GenerateChecksum(metadata *domains.DatabaseMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChecksum", metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChecksum indicates an expected call of GenerateChecksum.
func (mr *MockHashPortMockRecorder) GenerateChecksum(metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChecksum", reflect.TypeOf((*MockHashPort)(nil).GenerateChecksum), metadata)
}

// GenerateTenantID mocks base method.
func (m *MockHashPort) GenerateTenantID(dbUrl string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTenantID", dbUrl)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateTenantID indicates an expected call of GenerateTenantID.
func (mr *MockHashPortMockRecorder) GenerateTenantID(dbUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTenantID", reflect.TypeOf((*MockHashPort)(nil).GenerateTenantID), dbUrl)
}
