// Code generated by MockGen. DO NOT EDIT.
// Source: ports/encrypt.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncryptPort is a mock of EncryptPort interface.
type MockEncryptPort struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptPortMockRecorder
}

// MockEncryptPortMockRecorder is the mock recorder for MockEncryptPort.
type MockEncryptPortMockRecorder struct {
	mock *MockEncryptPort
}

// NewMockEncryptPort creates a new mock instance.
func NewMockEncryptPort(ctrl *gomock.Controller) *MockEncryptPort {
	mock := &MockEncryptPort{ctrl: ctrl}
	mock.recorder = &MockEncryptPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptPort) EXPECT() *MockEncryptPortMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptPort) Decrypt(cipherText string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", cipherText)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptPortMockRecorder) Decrypt(cipherText interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptPort)(nil).Decrypt), cipherText)
}

// Encrypt mocks base method.
func (m *MockEncryptPort) Encrypt(plainText string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plainText)
	ret0, _ := ret[0].(string)
	return ret0
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptPortMockRecorder) Encrypt(plainText interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptPort)(nil).Encrypt), plainText)
}
