// Code generated by MockGen. DO NOT EDIT.
// Source: ports/embedder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmbedderPort is a mock of EmbedderPort interface.
type MockEmbedderPort struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderPortMockRecorder
}

// MockEmbedderPortMockRecorder is the mock recorder for MockEmbedderPort.
type MockEmbedderPortMockRecorder struct {
	mock *MockEmbedderPort
}

// NewMockEmbedderPort creates a new mock instance.
func NewMockEmbedderPort(ctrl *gomock.Controller) *MockEmbedderPort {
	mock := &MockEmbedderPort{ctrl: ctrl}
	mock.recorder = &MockEmbedderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedderPort) EXPECT() *MockEmbedderPortMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockEmbedderPort) Embed(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbedderPortMockRecorder) Embed(ctx, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbedderPort)(nil).Embed), ctx, text)
}

// EmbedBatch mocks base method.
func (m *MockEmbedderPort) EmbedBatch(ctx context.Context, texts []string) ([][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedBatch", ctx, texts)
	ret0, _ := ret[0].([][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedBatch indicates an expected call of EmbedBatch.
func (mr *MockEmbedderPortMockRecorder) EmbedBatch(ctx, texts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedBatch", reflect.TypeOf((*MockEmbedderPort)(nil).EmbedBatch), ctx, texts)
}
