// Code generated by MockGen. DO NOT EDIT.
// Source: ports/internal_database.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockInternalDatabasePort is a mock of InternalDatabasePort interface.
type MockInternalDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockInternalDatabasePortMockRecorder
}

// MockInternalDatabasePortMockRecorder is the mock recorder for MockInternalDatabasePort.
type MockInternalDatabasePortMockRecorder struct {
	mock *MockInternalDatabasePort
}

// NewMockInternalDatabasePort creates a new mock instance.
func NewMockInternalDatabasePort(ctrl *gomock.Controller) *MockInternalDatabasePort {
	mock := &MockInternalDatabasePort{ctrl: ctrl}
	mock.recorder = &MockInternalDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternalDatabasePort) EXPECT() *MockInternalDatabasePortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInternalDatabasePort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInternalDatabasePortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInternalDatabasePort)(nil).Close))
}

// Connect mocks base method.
func (m *MockInternalDatabasePort) Connect(ctx context.Context, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockInternalDatabasePortMockRecorder) Connect(ctx, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockInternalDatabasePort)(nil).Connect), ctx, dbURL)
}

// GetWorkspaceByTenantID mocks base method.
func (m *MockInternalDatabasePort) GetWorkspaceByTenantID(ctx context.Context, tenantID string) (*domains.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceByTenantID", ctx, tenantID)
	ret0, _ := ret[0].(*domains.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceByTenantID indicates an expected call of GetWorkspaceByTenantID.
func (mr *MockInternalDatabasePortMockRecorder) GetWorkspaceByTenantID(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceByTenantID", reflect.TypeOf((*MockInternalDatabasePort)(nil).GetWorkspaceByTenantID), ctx, tenantID)
}

// UpsertWorkspace mocks base method.
func (m *MockInternalDatabasePort) UpsertWorkspace(ctx context.Context, workspace *domains.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorkspace", ctx, workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWorkspace indicates an expected call of UpsertWorkspace.
func (mr *MockInternalDatabasePortMockRecorder) UpsertWorkspace(ctx, workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorkspace", reflect.TypeOf((*MockInternalDatabasePort)(nil).UpsertWorkspace), ctx, workspace)
}
