// Code generated by MockGen. DO NOT EDIT.
// Source: ports/status.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockStatusPort is a mock of StatusPort interface.
type MockStatusPort struct {
	ctrl     *gomock.Controller
	recorder *MockStatusPortMockRecorder
}

// MockStatusPortMockRecorder is the mock recorder for MockStatusPort.
type MockStatusPortMockRecorder struct {
	mock *MockStatusPort
}

// NewMockStatusPort creates a new mock instance.
func NewMockStatusPort(ctrl *gomock.Controller) *MockStatusPort {
	mock := &MockStatusPort{ctrl: ctrl}
	mock.recorder = &MockStatusPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusPort) EXPECT() *MockStatusPortMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockStatusPort) Clear(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockStatusPortMockRecorder) Clear(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockStatusPort)(nil).Clear), ctx, tenantID)
}

// GetStatus mocks base method.
func (m *MockStatusPort) GetStatus(ctx context.Context, tenantID string) (domains.WorkspaceStatus, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, tenantID)
	ret0, _ := ret[0].(domains.WorkspaceStatus)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockStatusPortMockRecorder) GetStatus(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockStatusPort)(nil).GetStatus), ctx, tenantID)
}

// SetDone mocks base method.
func (m *MockStatusPort) SetDone(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDone", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDone indicates an expected call of SetDone.
func (mr *MockStatusPortMockRecorder) SetDone(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDone", reflect.TypeOf((*MockStatusPort)(nil).SetDone), ctx, tenantID)
}

// SetError mocks base method.
func (m *MockStatusPort) SetError(ctx context.Context, tenantID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetError", ctx, tenantID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetError indicates an expected call of SetError.
func (mr *MockStatusPortMockRecorder) SetError(ctx, tenantID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetError", reflect.TypeOf((*MockStatusPort)(nil).SetError), ctx, tenantID, message)
}

// SetInProgress mocks base method.
func (m *MockStatusPort) SetInProgress(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInProgress", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInProgress indicates an expected call of SetInProgress.
func (mr *MockStatusPortMockRecorder) SetInProgress(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInProgress", reflect.TypeOf((*MockStatusPort)(nil).SetInProgress), ctx, tenantID)
}

// SetWarn mocks base method.
func (m *MockStatusPort) SetWarn(ctx context.Context, tenantID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWarn", ctx, tenantID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWarn indicates an expected call of SetWarn.
func (mr *MockStatusPortMockRecorder) SetWarn(ctx, tenantID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarn", reflect.TypeOf((*MockStatusPort)(nil).SetWarn), ctx, tenantID, message)
}
