// Code generated by MockGen. DO NOT EDIT.
// Source: ports/taskqueue.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskQueuePort is a mock of TaskQueuePort interface.
type MockTaskQueuePort struct {
	ctrl     *gomock.Controller
	recorder *MockTaskQueuePortMockRecorder
}

// MockTaskQueuePortMockRecorder is the mock recorder for MockTaskQueuePort.
type MockTaskQueuePortMockRecorder struct {
	mock *MockTaskQueuePort
}

// NewMockTaskQueuePort creates a new mock instance.
func NewMockTaskQueuePort(ctrl *gomock.Controller) *MockTaskQueuePort {
	mock := &MockTaskQueuePort{ctrl: ctrl}
	mock.recorder = &MockTaskQueuePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskQueuePort) EXPECT() *MockTaskQueuePortMockRecorder {
	return m.recorder
}

// EnqueueIngestionTask mocks base method.
func (m *MockTaskQueuePort) EnqueueIngestionTask(ctx context.Context, tenantID, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueIngestionTask", ctx, tenantID, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueIngestionTask indicates an expected call of EnqueueIngestionTask.
func (mr *MockTaskQueuePortMockRecorder) EnqueueIngestionTask(ctx, tenantID, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueIngestionTask", reflect.TypeOf((*MockTaskQueuePort)(nil).EnqueueIngestionTask), ctx, tenantID, dbURL)
}
