// Code generated by MockGen. DO NOT EDIT.
// Source: ports/taskqueue.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskQueueService is a mock of TaskQueueService interface.
type MockTaskQueueService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskQueueServiceMockRecorder
}

// MockTaskQueueServiceMockRecorder is the mock recorder for MockTaskQueueService.
type MockTaskQueueServiceMockRecorder struct {
	mock *MockTaskQueueService
}

// NewMockTaskQueueService creates a new mock instance.
func NewMockTaskQueueService(ctrl *gomock.Controller) *MockTaskQueueService {
	mock := &MockTaskQueueService{ctrl: ctrl}
	mock.recorder = &MockTaskQueueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskQueueService) EXPECT() *MockTaskQueueServiceMockRecorder {
	return m.recorder
}

// EnqueueIngestionTask mocks base method.
func (m *MockTaskQueueService) EnqueueIngestionTask(ctx context.Context, tenantID, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueIngestionTask", ctx, tenantID, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueIngestionTask indicates an expected call of EnqueueIngestionTask.
func (mr *MockTaskQueueServiceMockRecorder) EnqueueIngestionTask(ctx, tenantID, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueIngestionTask", reflect.TypeOf((*MockTaskQueueService)(nil).EnqueueIngestionTask), ctx, tenantID, dbURL)
}
