// Code generated by MockGen. DO NOT EDIT.
// Source: ports/client_database.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockClientDatabasePort is a mock of ClientDatabasePort interface.
type MockClientDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockClientDatabasePortMockRecorder
}

// MockClientDatabasePortMockRecorder is the mock recorder for MockClientDatabasePort.
type MockClientDatabasePortMockRecorder struct {
	mock *MockClientDatabasePort
}

// NewMockClientDatabasePort creates a new mock instance.
func NewMockClientDatabasePort(ctrl *gomock.Controller) *MockClientDatabasePort {
	mock := &MockClientDatabasePort{ctrl: ctrl}
	mock.recorder = &MockClientDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientDatabasePort) EXPECT() *MockClientDatabasePortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientDatabasePort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientDatabasePortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientDatabasePort)(nil).Close))
}

// Connect mocks base method.
func (m *MockClientDatabasePort) Connect(ctx context.Context, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockClientDatabasePortMockRecorder) Connect(ctx, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockClientDatabasePort)(nil).Connect), ctx, dbURL)
}

// Execute mocks base method.
func (m *MockClientDatabasePort) Execute(ctx context.Context, query string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, query)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockClientDatabasePortMockRecorder) Execute(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockClientDatabasePort)(nil).Execute), ctx, query)
}

// ExecuteDryRun mocks base method.
func (m *MockClientDatabasePort) ExecuteDryRun(ctx context.Context, query string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDryRun", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteDryRun indicates an expected call of ExecuteDryRun.
func (mr *MockClientDatabasePortMockRecorder) ExecuteDryRun(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDryRun", reflect.TypeOf((*MockClientDatabasePort)(nil).ExecuteDryRun), ctx, query)
}

// GetDatabaseMetadata mocks base method.
func (m *MockClientDatabasePort) GetDatabaseMetadata(ctx context.Context) (*domains.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseMetadata", ctx)
	ret0, _ := ret[0].(*domains.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseMetadata indicates an expected call of GetDatabaseMetadata.
func (mr *MockClientDatabasePortMockRecorder) GetDatabaseMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseMetadata", reflect.TypeOf((*MockClientDatabasePort)(nil).GetDatabaseMetadata), ctx)
}
