// Code generated by MockGen. DO NOT EDIT.
// Source: ports/vector_store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockVectorStorePort is a mock of VectorStorePort interface.
type MockVectorStorePort struct {
	ctrl     *gomock.Controller
	recorder *MockVectorStorePortMockRecorder
}

// MockVectorStorePortMockRecorder is the mock recorder for MockVectorStorePort.
type MockVectorStorePortMockRecorder struct {
	mock *MockVectorStorePort
}

// NewMockVectorStorePort creates a new mock instance.
func NewMockVectorStorePort(ctrl *gomock.Controller) *MockVectorStorePort {
	mock := &MockVectorStorePort{ctrl: ctrl}
	mock.recorder = &MockVectorStorePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorStorePort) EXPECT() *MockVectorStorePortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockVectorStorePort) Delete(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVectorStorePortMockRecorder) Delete(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVectorStorePort)(nil).Delete), ctx, tenantID)
}

// Exists mocks base method.
func (m *MockVectorStorePort) Exists(ctx context.Context, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockVectorStorePortMockRecorder) Exists(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockVectorStorePort)(nil).Exists), ctx, tenantID)
}

// Search mocks base method.
func (m *MockVectorStorePort) Search(ctx context.Context, tenantID string, queryEmbedding []float32, limit int) ([]domains.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, tenantID, queryEmbedding, limit)
	ret0, _ := ret[0].([]domains.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockVectorStorePortMockRecorder) Search(ctx, tenantID, queryEmbedding, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockVectorStorePort)(nil).Search), ctx, tenantID, queryEmbedding, limit)
}

// Upsert mocks base method.
func (m *MockVectorStorePort) Upsert(ctx context.Context, tenantID string, vectors []domains.Vector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tenantID, vectors)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockVectorStorePortMockRecorder) Upsert(ctx, tenantID, vectors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockVectorStorePort)(nil).Upsert), ctx, tenantID, vectors)
}
