// Code generated by MockGen. DO NOT EDIT.
// Source: ports/query.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// PromptToQueryData mocks base method.
func (m *MockQueryService) PromptToQueryData(ctx context.Context, tenantID, prompt string, withData bool) (*domains.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptToQueryData", ctx, tenantID, prompt, withData)
	ret0, _ := ret[0].(*domains.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptToQueryData indicates an expected call of PromptToQueryData.
func (mr *MockQueryServiceMockRecorder) PromptToQueryData(ctx, tenantID, prompt, withData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptToQueryData", reflect.TypeOf((*MockQueryService)(nil).PromptToQueryData), ctx, tenantID, prompt, withData)
}
