// Code generated by MockGen. DO NOT EDIT.
// Source: ports/llm.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockLLMPort is a mock of LLMPort interface.
type MockLLMPort struct {
	ctrl     *gomock.Controller
	recorder *MockLLMPortMockRecorder
}

// MockLLMPortMockRecorder is the mock recorder for MockLLMPort.
type MockLLMPortMockRecorder struct {
	mock *MockLLMPort
}

// NewMockLLMPort creates a new mock instance.
func NewMockLLMPort(ctrl *gomock.Controller) *MockLLMPort {
	mock := &MockLLMPort{ctrl: ctrl}
	mock.recorder = &MockLLMPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMPort) EXPECT() *MockLLMPortMockRecorder {
	return m.recorder
}

// GenerateQuery mocks base method.
func (m *MockLLMPort) GenerateQuery(ctx context.Context, prompt string, contexts []domains.Vector, additionalPrompts ...string) (*string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, prompt, contexts}
	for _, a := range additionalPrompts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateQuery", varargs...)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateQuery indicates an expected call of GenerateQuery.
func (mr *MockLLMPortMockRecorder) GenerateQuery(ctx, prompt, contexts interface{}, additionalPrompts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, prompt, contexts}, additionalPrompts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQuery", reflect.TypeOf((*MockLLMPort)(nil).GenerateQuery), varargs...)
}
