// Code generated by MockGen. DO NOT EDIT.
// Source: ports/embedder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmbedderRepository is a mock of EmbedderRepository interface.
type MockEmbedderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderRepositoryMockRecorder
}

// MockEmbedderRepositoryMockRecorder is the mock recorder for MockEmbedderRepository.
type MockEmbedderRepositoryMockRecorder struct {
	mock *MockEmbedderRepository
}

// NewMockEmbedderRepository creates a new mock instance.
func NewMockEmbedderRepository(ctrl *gomock.Controller) *MockEmbedderRepository {
	mock := &MockEmbedderRepository{ctrl: ctrl}
	mock.recorder = &MockEmbedderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedderRepository) EXPECT() *MockEmbedderRepositoryMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockEmbedderRepository) Embed(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbedderRepositoryMockRecorder) Embed(ctx, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbedderRepository)(nil).Embed), ctx, text)
}

// EmbedBatch mocks base method.
func (m *MockEmbedderRepository) EmbedBatch(ctx context.Context, texts []string) ([][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedBatch", ctx, texts)
	ret0, _ := ret[0].([][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedBatch indicates an expected call of EmbedBatch.
func (mr *MockEmbedderRepositoryMockRecorder) EmbedBatch(ctx, texts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedBatch", reflect.TypeOf((*MockEmbedderRepository)(nil).EmbedBatch), ctx, texts)
}
