// Code generated by MockGen. DO NOT EDIT.
// Source: ports/client_database.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientDatabaseRepository is a mock of ClientDatabaseRepository interface.
type MockClientDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientDatabaseRepositoryMockRecorder
}

// MockClientDatabaseRepositoryMockRecorder is the mock recorder for MockClientDatabaseRepository.
type MockClientDatabaseRepositoryMockRecorder struct {
	mock *MockClientDatabaseRepository
}

// NewMockClientDatabaseRepository creates a new mock instance.
func NewMockClientDatabaseRepository(ctrl *gomock.Controller) *MockClientDatabaseRepository {
	mock := &MockClientDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockClientDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientDatabaseRepository) EXPECT() *MockClientDatabaseRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientDatabaseRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientDatabaseRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientDatabaseRepository)(nil).Close))
}

// Connect mocks base method.
func (m *MockClientDatabaseRepository) Connect(ctx context.Context, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockClientDatabaseRepositoryMockRecorder) Connect(ctx, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockClientDatabaseRepository)(nil).Connect), ctx, dbURL)
}

// Execute mocks base method.
func (m *MockClientDatabaseRepository) Execute(ctx context.Context, query string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, query)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockClientDatabaseRepositoryMockRecorder) Execute(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockClientDatabaseRepository)(nil).Execute), ctx, query)
}

// ExecuteDryRun mocks base method.
func (m *MockClientDatabaseRepository) ExecuteDryRun(ctx context.Context, query string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDryRun", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteDryRun indicates an expected call of ExecuteDryRun.
func (mr *MockClientDatabaseRepositoryMockRecorder) ExecuteDryRun(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDryRun", reflect.TypeOf((*MockClientDatabaseRepository)(nil).ExecuteDryRun), ctx, query)
}
