// Code generated by MockGen. DO NOT EDIT.
// Source: ports/vector_store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domains "github.com/kamil5b/go-nl2query-lib/domains"
)

// MockVectorStoreRepository is a mock of VectorStoreRepository interface.
type MockVectorStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVectorStoreRepositoryMockRecorder
}

// MockVectorStoreRepositoryMockRecorder is the mock recorder for MockVectorStoreRepository.
type MockVectorStoreRepositoryMockRecorder struct {
	mock *MockVectorStoreRepository
}

// NewMockVectorStoreRepository creates a new mock instance.
func NewMockVectorStoreRepository(ctrl *gomock.Controller) *MockVectorStoreRepository {
	mock := &MockVectorStoreRepository{ctrl: ctrl}
	mock.recorder = &MockVectorStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorStoreRepository) EXPECT() *MockVectorStoreRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockVectorStoreRepository) Delete(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVectorStoreRepositoryMockRecorder) Delete(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVectorStoreRepository)(nil).Delete), ctx, tenantID)
}

// Exists mocks base method.
func (m *MockVectorStoreRepository) Exists(ctx context.Context, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockVectorStoreRepositoryMockRecorder) Exists(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockVectorStoreRepository)(nil).Exists), ctx, tenantID)
}

// Search mocks base method.
func (m *MockVectorStoreRepository) Search(ctx context.Context, tenantID string, queryEmbedding []float32, limit int) ([]domains.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, tenantID, queryEmbedding, limit)
	ret0, _ := ret[0].([]domains.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockVectorStoreRepositoryMockRecorder) Search(ctx, tenantID, queryEmbedding, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockVectorStoreRepository)(nil).Search), ctx, tenantID, queryEmbedding, limit)
}

// Upsert mocks base method.
func (m *MockVectorStoreRepository) Upsert(ctx context.Context, tenantID string, vectors []domains.Vector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tenantID, vectors)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockVectorStoreRepositoryMockRecorder) Upsert(ctx, tenantID, vectors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockVectorStoreRepository)(nil).Upsert), ctx, tenantID, vectors)
}
