// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/llm.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLLMRepository is a mock of LLMRepository interface.
type MockLLMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLLMRepositoryMockRecorder
}

// MockLLMRepositoryMockRecorder is the mock recorder for MockLLMRepository.
type MockLLMRepositoryMockRecorder struct {
	mock *MockLLMRepository
}

// NewMockLLMRepository creates a new mock instance.
func NewMockLLMRepository(ctrl *gomock.Controller) *MockLLMRepository {
	mock := &MockLLMRepository{ctrl: ctrl}
	mock.recorder = &MockLLMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMRepository) EXPECT() *MockLLMRepositoryMockRecorder {
	return m.recorder
}

// CorrectQuery mocks base method.
func (m *MockLLMRepository) CorrectQuery(ctx context.Context, prompt, invalidSQL string, errors []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CorrectQuery", ctx, prompt, invalidSQL, errors)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CorrectQuery indicates an expected call of CorrectQuery.
func (mr *MockLLMRepositoryMockRecorder) CorrectQuery(ctx, prompt, invalidSQL, errors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CorrectQuery", reflect.TypeOf((*MockLLMRepository)(nil).CorrectQuery), ctx, prompt, invalidSQL, errors)
}

// GenerateQuery mocks base method.
func (m *MockLLMRepository) GenerateQuery(ctx context.Context, prompt, context string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQuery", ctx, prompt, context)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateQuery indicates an expected call of GenerateQuery.
func (mr *MockLLMRepositoryMockRecorder) GenerateQuery(ctx, prompt, context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQuery", reflect.TypeOf((*MockLLMRepository)(nil).GenerateQuery), ctx, prompt, context)
}
