// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/llm.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLLMRepository is a mock of LLMRepository interface.
type MockLLMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLLMRepositoryMockRecorder
}

// MockLLMRepositoryMockRecorder is the mock recorder for MockLLMRepository.
type MockLLMRepositoryMockRecorder struct {
	mock *MockLLMRepository
}

// NewMockLLMRepository creates a new mock instance.
func NewMockLLMRepository(ctrl *gomock.Controller) *MockLLMRepository {
	mock := &MockLLMRepository{ctrl: ctrl}
	mock.recorder = &MockLLMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMRepository) EXPECT() *MockLLMRepositoryMockRecorder {
	return m.recorder
}

// CorrectSQL mocks base method.
func (m *MockLLMRepository) CorrectSQL(ctx context.Context, prompt, invalidSQL string, error []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CorrectSQL", ctx, prompt, invalidSQL, error)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CorrectSQL indicates an expected call of CorrectSQL.
func (mr *MockLLMRepositoryMockRecorder) CorrectSQL(ctx, prompt, invalidSQL, error interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CorrectSQL", reflect.TypeOf((*MockLLMRepository)(nil).CorrectSQL), ctx, prompt, invalidSQL, error)
}

// GenerateSQL mocks base method.
func (m *MockLLMRepository) GenerateSQL(ctx context.Context, prompt, context string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSQL", ctx, prompt, context)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSQL indicates an expected call of GenerateSQL.
func (mr *MockLLMRepositoryMockRecorder) GenerateSQL(ctx, prompt, context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSQL", reflect.TypeOf((*MockLLMRepository)(nil).GenerateSQL), ctx, prompt, context)
}
