// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/status.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStatusRepository is a mock of StatusRepository interface.
type MockStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatusRepositoryMockRecorder
}

// MockStatusRepositoryMockRecorder is the mock recorder for MockStatusRepository.
type MockStatusRepositoryMockRecorder struct {
	mock *MockStatusRepository
}

// NewMockStatusRepository creates a new mock instance.
func NewMockStatusRepository(ctrl *gomock.Controller) *MockStatusRepository {
	mock := &MockStatusRepository{ctrl: ctrl}
	mock.recorder = &MockStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusRepository) EXPECT() *MockStatusRepositoryMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockStatusRepository) Clear(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockStatusRepositoryMockRecorder) Clear(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockStatusRepository)(nil).Clear), ctx, tenantID)
}

// GetStatus mocks base method.
func (m *MockStatusRepository) GetStatus(ctx context.Context, tenantID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, tenantID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockStatusRepositoryMockRecorder) GetStatus(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockStatusRepository)(nil).GetStatus), ctx, tenantID)
}

// SetDone mocks base method.
func (m *MockStatusRepository) SetDone(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDone", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDone indicates an expected call of SetDone.
func (mr *MockStatusRepositoryMockRecorder) SetDone(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDone", reflect.TypeOf((*MockStatusRepository)(nil).SetDone), ctx, tenantID)
}

// SetError mocks base method.
func (m *MockStatusRepository) SetError(ctx context.Context, tenantID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetError", ctx, tenantID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetError indicates an expected call of SetError.
func (mr *MockStatusRepositoryMockRecorder) SetError(ctx, tenantID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetError", reflect.TypeOf((*MockStatusRepository)(nil).SetError), ctx, tenantID, message)
}

// SetInProgress mocks base method.
func (m *MockStatusRepository) SetInProgress(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInProgress", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInProgress indicates an expected call of SetInProgress.
func (mr *MockStatusRepositoryMockRecorder) SetInProgress(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInProgress", reflect.TypeOf((*MockStatusRepository)(nil).SetInProgress), ctx, tenantID)
}

// SetWarn mocks base method.
func (m *MockStatusRepository) SetWarn(ctx context.Context, tenantID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWarn", ctx, tenantID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWarn indicates an expected call of SetWarn.
func (mr *MockStatusRepositoryMockRecorder) SetWarn(ctx, tenantID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarn", reflect.TypeOf((*MockStatusRepository)(nil).SetWarn), ctx, tenantID, message)
}
