// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/workspace.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockWorkspaceService is a mock of WorkspaceService interface.
type MockWorkspaceService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceServiceMockRecorder
}

// MockWorkspaceServiceMockRecorder is the mock recorder for MockWorkspaceService.
type MockWorkspaceServiceMockRecorder struct {
	mock *MockWorkspaceService
}

// NewMockWorkspaceService creates a new mock instance.
func NewMockWorkspaceService(ctrl *gomock.Controller) *MockWorkspaceService {
	mock := &MockWorkspaceService{ctrl: ctrl}
	mock.recorder = &MockWorkspaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceService) EXPECT() *MockWorkspaceServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockWorkspaceService) Delete(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkspaceServiceMockRecorder) Delete(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkspaceService)(nil).Delete), ctx, tenantID)
}

// GetByTenantID mocks base method.
func (m *MockWorkspaceService) GetByTenantID(ctx context.Context, tenantID string) (*model.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantID", ctx, tenantID)
	ret0, _ := ret[0].(*model.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantID indicates an expected call of GetByTenantID.
func (mr *MockWorkspaceServiceMockRecorder) GetByTenantID(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantID", reflect.TypeOf((*MockWorkspaceService)(nil).GetByTenantID), ctx, tenantID)
}

// ListAll mocks base method.
func (m *MockWorkspaceService) ListAll(ctx context.Context) ([]*model.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*model.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockWorkspaceServiceMockRecorder) ListAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockWorkspaceService)(nil).ListAll), ctx)
}

// Save mocks base method.
func (m *MockWorkspaceService) Save(ctx context.Context, workspace *model.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockWorkspaceServiceMockRecorder) Save(ctx, workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockWorkspaceService)(nil).Save), ctx, workspace)
}

// Update mocks base method.
func (m *MockWorkspaceService) Update(ctx context.Context, workspace *model.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkspaceServiceMockRecorder) Update(ctx, workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkspaceService)(nil).Update), ctx, workspace)
}
