// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/sql_validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSQLValidatorRepository is a mock of SQLValidatorRepository interface.
type MockSQLValidatorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSQLValidatorRepositoryMockRecorder
}

// MockSQLValidatorRepositoryMockRecorder is the mock recorder for MockSQLValidatorRepository.
type MockSQLValidatorRepositoryMockRecorder struct {
	mock *MockSQLValidatorRepository
}

// NewMockSQLValidatorRepository creates a new mock instance.
func NewMockSQLValidatorRepository(ctrl *gomock.Controller) *MockSQLValidatorRepository {
	mock := &MockSQLValidatorRepository{ctrl: ctrl}
	mock.recorder = &MockSQLValidatorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLValidatorRepository) EXPECT() *MockSQLValidatorRepositoryMockRecorder {
	return m.recorder
}

// ContainsDDLDML mocks base method.
func (m *MockSQLValidatorRepository) ContainsDDLDML(sql string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsDDLDML", sql)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsDDLDML indicates an expected call of ContainsDDLDML.
func (mr *MockSQLValidatorRepositoryMockRecorder) ContainsDDLDML(sql interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsDDLDML", reflect.TypeOf((*MockSQLValidatorRepository)(nil).ContainsDDLDML), sql)
}

// IsSafe mocks base method.
func (m *MockSQLValidatorRepository) IsSafe(sql string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSafe", sql)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSafe indicates an expected call of IsSafe.
func (mr *MockSQLValidatorRepositoryMockRecorder) IsSafe(sql interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSafe", reflect.TypeOf((*MockSQLValidatorRepository)(nil).IsSafe), sql)
}
