// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/hash.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockHashRepository is a mock of HashRepository interface.
type MockHashRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHashRepositoryMockRecorder
}

// MockHashRepositoryMockRecorder is the mock recorder for MockHashRepository.
type MockHashRepositoryMockRecorder struct {
	mock *MockHashRepository
}

// NewMockHashRepository creates a new mock instance.
func NewMockHashRepository(ctrl *gomock.Controller) *MockHashRepository {
	mock := &MockHashRepository{ctrl: ctrl}
	mock.recorder = &MockHashRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashRepository) EXPECT() *MockHashRepositoryMockRecorder {
	return m.recorder
}

// GenerateChecksum mocks base method.
func (m *MockHashRepository) GenerateChecksum(metadata *model.DatabaseMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChecksum", metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChecksum indicates an expected call of GenerateChecksum.
func (mr *MockHashRepositoryMockRecorder) GenerateChecksum(metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChecksum", reflect.TypeOf((*MockHashRepository)(nil).GenerateChecksum), metadata)
}

// GenerateTenantID mocks base method.
func (m *MockHashRepository) GenerateTenantID(dbUrl string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTenantID", dbUrl)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateTenantID indicates an expected call of GenerateTenantID.
func (mr *MockHashRepositoryMockRecorder) GenerateTenantID(dbUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTenantID", reflect.TypeOf((*MockHashRepository)(nil).GenerateTenantID), dbUrl)
}
