// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/encryptor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockEncryptorRepository is a mock of EncryptorRepository interface.
type MockEncryptorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorRepositoryMockRecorder
}

// MockEncryptorRepositoryMockRecorder is the mock recorder for MockEncryptorRepository.
type MockEncryptorRepositoryMockRecorder struct {
	mock *MockEncryptorRepository
}

// NewMockEncryptorRepository creates a new mock instance.
func NewMockEncryptorRepository(ctrl *gomock.Controller) *MockEncryptorRepository {
	mock := &MockEncryptorRepository{ctrl: ctrl}
	mock.recorder = &MockEncryptorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptorRepository) EXPECT() *MockEncryptorRepositoryMockRecorder {
	return m.recorder
}

// GenerateChecksum mocks base method.
func (m *MockEncryptorRepository) GenerateChecksum(metadata *model.DatabaseMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChecksum", metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChecksum indicates an expected call of GenerateChecksum.
func (mr *MockEncryptorRepositoryMockRecorder) GenerateChecksum(metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChecksum", reflect.TypeOf((*MockEncryptorRepository)(nil).GenerateChecksum), metadata)
}

// GenerateTenantID mocks base method.
func (m *MockEncryptorRepository) GenerateTenantID(dbUrl string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTenantID", dbUrl)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateTenantID indicates an expected call of GenerateTenantID.
func (mr *MockEncryptorRepositoryMockRecorder) GenerateTenantID(dbUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTenantID", reflect.TypeOf((*MockEncryptorRepository)(nil).GenerateTenantID), dbUrl)
}
