// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/database_connection.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseConnection is a mock of DatabaseConnection interface.
type MockDatabaseConnection struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseConnectionMockRecorder
}

// MockDatabaseConnectionMockRecorder is the mock recorder for MockDatabaseConnection.
type MockDatabaseConnectionMockRecorder struct {
	mock *MockDatabaseConnection
}

// NewMockDatabaseConnection creates a new mock instance.
func NewMockDatabaseConnection(ctrl *gomock.Controller) *MockDatabaseConnection {
	mock := &MockDatabaseConnection{ctrl: ctrl}
	mock.recorder = &MockDatabaseConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseConnection) EXPECT() *MockDatabaseConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDatabaseConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaseConnection)(nil).Close))
}

// Connect mocks base method.
func (m *MockDatabaseConnection) Connect(ctx context.Context, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockDatabaseConnectionMockRecorder) Connect(ctx, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDatabaseConnection)(nil).Connect), ctx, dbURL)
}

// Execute mocks base method.
func (m *MockDatabaseConnection) Execute(ctx context.Context, query string) ([]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, query)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDatabaseConnectionMockRecorder) Execute(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDatabaseConnection)(nil).Execute), ctx, query)
}

// ExecuteDryRun mocks base method.
func (m *MockDatabaseConnection) ExecuteDryRun(ctx context.Context, query string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDryRun", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteDryRun indicates an expected call of ExecuteDryRun.
func (mr *MockDatabaseConnectionMockRecorder) ExecuteDryRun(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDryRun", reflect.TypeOf((*MockDatabaseConnection)(nil).ExecuteDryRun), ctx, query)
}

// Ping mocks base method.
func (m *MockDatabaseConnection) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabaseConnectionMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabaseConnection)(nil).Ping), ctx)
}
