// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/internal_database.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockInternalDatabaseRepository is a mock of InternalDatabaseRepository interface.
type MockInternalDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInternalDatabaseRepositoryMockRecorder
}

// MockInternalDatabaseRepositoryMockRecorder is the mock recorder for MockInternalDatabaseRepository.
type MockInternalDatabaseRepositoryMockRecorder struct {
	mock *MockInternalDatabaseRepository
}

// NewMockInternalDatabaseRepository creates a new mock instance.
func NewMockInternalDatabaseRepository(ctrl *gomock.Controller) *MockInternalDatabaseRepository {
	mock := &MockInternalDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockInternalDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternalDatabaseRepository) EXPECT() *MockInternalDatabaseRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInternalDatabaseRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInternalDatabaseRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInternalDatabaseRepository)(nil).Close))
}

// Connect mocks base method.
func (m *MockInternalDatabaseRepository) Connect(ctx context.Context, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockInternalDatabaseRepositoryMockRecorder) Connect(ctx, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockInternalDatabaseRepository)(nil).Connect), ctx, dbURL)
}

// GetWorkspaceByTenantID mocks base method.
func (m *MockInternalDatabaseRepository) GetWorkspaceByTenantID(ctx context.Context, tenantID string) (*model.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceByTenantID", ctx, tenantID)
	ret0, _ := ret[0].(*model.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceByTenantID indicates an expected call of GetWorkspaceByTenantID.
func (mr *MockInternalDatabaseRepositoryMockRecorder) GetWorkspaceByTenantID(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceByTenantID", reflect.TypeOf((*MockInternalDatabaseRepository)(nil).GetWorkspaceByTenantID), ctx, tenantID)
}

// UpsertWorkspace mocks base method.
func (m *MockInternalDatabaseRepository) UpsertWorkspace(ctx context.Context, workspace *model.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorkspace", ctx, workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWorkspace indicates an expected call of UpsertWorkspace.
func (mr *MockInternalDatabaseRepositoryMockRecorder) UpsertWorkspace(ctx, workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorkspace", reflect.TypeOf((*MockInternalDatabaseRepository)(nil).UpsertWorkspace), ctx, workspace)
}
