// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/taskqueue.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskQueue is a mock of TaskQueue interface.
type MockTaskQueue struct {
	ctrl     *gomock.Controller
	recorder *MockTaskQueueMockRecorder
}

// MockTaskQueueMockRecorder is the mock recorder for MockTaskQueue.
type MockTaskQueueMockRecorder struct {
	mock *MockTaskQueue
}

// NewMockTaskQueue creates a new mock instance.
func NewMockTaskQueue(ctrl *gomock.Controller) *MockTaskQueue {
	mock := &MockTaskQueue{ctrl: ctrl}
	mock.recorder = &MockTaskQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskQueue) EXPECT() *MockTaskQueueMockRecorder {
	return m.recorder
}

// EnqueueIngestionTask mocks base method.
func (m *MockTaskQueue) EnqueueIngestionTask(ctx context.Context, tenantID, dbURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueIngestionTask", ctx, tenantID, dbURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueIngestionTask indicates an expected call of EnqueueIngestionTask.
func (mr *MockTaskQueueMockRecorder) EnqueueIngestionTask(ctx, tenantID, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueIngestionTask", reflect.TypeOf((*MockTaskQueue)(nil).EnqueueIngestionTask), ctx, tenantID, dbURL)
}
