// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/query_validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQueryValidatorRepository is a mock of QueryValidatorRepository interface.
type MockQueryValidatorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryValidatorRepositoryMockRecorder
}

// MockQueryValidatorRepositoryMockRecorder is the mock recorder for MockQueryValidatorRepository.
type MockQueryValidatorRepositoryMockRecorder struct {
	mock *MockQueryValidatorRepository
}

// NewMockQueryValidatorRepository creates a new mock instance.
func NewMockQueryValidatorRepository(ctrl *gomock.Controller) *MockQueryValidatorRepository {
	mock := &MockQueryValidatorRepository{ctrl: ctrl}
	mock.recorder = &MockQueryValidatorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryValidatorRepository) EXPECT() *MockQueryValidatorRepositoryMockRecorder {
	return m.recorder
}

// ContainsDDLDML mocks base method.
func (m *MockQueryValidatorRepository) ContainsDDLDML(query string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsDDLDML", query)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsDDLDML indicates an expected call of ContainsDDLDML.
func (mr *MockQueryValidatorRepositoryMockRecorder) ContainsDDLDML(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsDDLDML", reflect.TypeOf((*MockQueryValidatorRepository)(nil).ContainsDDLDML), query)
}

// IsSafe mocks base method.
func (m *MockQueryValidatorRepository) IsSafe(query string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSafe", query)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSafe indicates an expected call of IsSafe.
func (mr *MockQueryValidatorRepositoryMockRecorder) IsSafe(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSafe", reflect.TypeOf((*MockQueryValidatorRepository)(nil).IsSafe), query)
}
