// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/checksum_generator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockChecksumGenerator is a mock of ChecksumGenerator interface.
type MockChecksumGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockChecksumGeneratorMockRecorder
}

// MockChecksumGeneratorMockRecorder is the mock recorder for MockChecksumGenerator.
type MockChecksumGeneratorMockRecorder struct {
	mock *MockChecksumGenerator
}

// NewMockChecksumGenerator creates a new mock instance.
func NewMockChecksumGenerator(ctrl *gomock.Controller) *MockChecksumGenerator {
	mock := &MockChecksumGenerator{ctrl: ctrl}
	mock.recorder = &MockChecksumGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecksumGenerator) EXPECT() *MockChecksumGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockChecksumGenerator) Generate(metadata *model.DatabaseMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockChecksumGeneratorMockRecorder) Generate(metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockChecksumGenerator)(nil).Generate), metadata)
}
