// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/ingestion.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockIngestionService is a mock of IngestionService interface.
type MockIngestionService struct {
	ctrl     *gomock.Controller
	recorder *MockIngestionServiceMockRecorder
}

// MockIngestionServiceMockRecorder is the mock recorder for MockIngestionService.
type MockIngestionServiceMockRecorder struct {
	mock *MockIngestionService
}

// NewMockIngestionService creates a new mock instance.
func NewMockIngestionService(ctrl *gomock.Controller) *MockIngestionService {
	mock := &MockIngestionService{ctrl: ctrl}
	mock.recorder = &MockIngestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestionService) EXPECT() *MockIngestionServiceMockRecorder {
	return m.recorder
}

// VectorizeAndStore mocks base method.
func (m *MockIngestionService) VectorizeAndStore(ctx context.Context, metadata *model.DatabaseMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VectorizeAndStore", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// VectorizeAndStore indicates an expected call of VectorizeAndStore.
func (mr *MockIngestionServiceMockRecorder) VectorizeAndStore(ctx, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VectorizeAndStore", reflect.TypeOf((*MockIngestionService)(nil).VectorizeAndStore), ctx, metadata)
}
