// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/metadata_extractor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kamil5b/go-nl-sql/internal/domain/model"
)

// MockMetadataExtractor is a mock of MetadataExtractor interface.
type MockMetadataExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataExtractorMockRecorder
}

// MockMetadataExtractorMockRecorder is the mock recorder for MockMetadataExtractor.
type MockMetadataExtractorMockRecorder struct {
	mock *MockMetadataExtractor
}

// NewMockMetadataExtractor creates a new mock instance.
func NewMockMetadataExtractor(ctrl *gomock.Controller) *MockMetadataExtractor {
	mock := &MockMetadataExtractor{ctrl: ctrl}
	mock.recorder = &MockMetadataExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataExtractor) EXPECT() *MockMetadataExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockMetadataExtractor) Extract(ctx context.Context, dbURL string) (*model.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, dbURL)
	ret0, _ := ret[0].(*model.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockMetadataExtractorMockRecorder) Extract(ctx, dbURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockMetadataExtractor)(nil).Extract), ctx, dbURL)
}
