// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/sql_validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSQLValidator is a mock of SQLValidator interface.
type MockSQLValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSQLValidatorMockRecorder
}

// MockSQLValidatorMockRecorder is the mock recorder for MockSQLValidator.
type MockSQLValidatorMockRecorder struct {
	mock *MockSQLValidator
}

// NewMockSQLValidator creates a new mock instance.
func NewMockSQLValidator(ctrl *gomock.Controller) *MockSQLValidator {
	mock := &MockSQLValidator{ctrl: ctrl}
	mock.recorder = &MockSQLValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLValidator) EXPECT() *MockSQLValidatorMockRecorder {
	return m.recorder
}

// ContainsDDLDML mocks base method.
func (m *MockSQLValidator) ContainsDDLDML(sql string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsDDLDML", sql)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsDDLDML indicates an expected call of ContainsDDLDML.
func (mr *MockSQLValidatorMockRecorder) ContainsDDLDML(sql interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsDDLDML", reflect.TypeOf((*MockSQLValidator)(nil).ContainsDDLDML), sql)
}

// IsSafe mocks base method.
func (m *MockSQLValidator) IsSafe(sql string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSafe", sql)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSafe indicates an expected call of IsSafe.
func (mr *MockSQLValidatorMockRecorder) IsSafe(sql interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSafe", reflect.TypeOf((*MockSQLValidator)(nil).IsSafe), sql)
}
