// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/llm.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLLMService is a mock of LLMService interface.
type MockLLMService struct {
	ctrl     *gomock.Controller
	recorder *MockLLMServiceMockRecorder
}

// MockLLMServiceMockRecorder is the mock recorder for MockLLMService.
type MockLLMServiceMockRecorder struct {
	mock *MockLLMService
}

// NewMockLLMService creates a new mock instance.
func NewMockLLMService(ctrl *gomock.Controller) *MockLLMService {
	mock := &MockLLMService{ctrl: ctrl}
	mock.recorder = &MockLLMServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMService) EXPECT() *MockLLMServiceMockRecorder {
	return m.recorder
}

// CorrectSQL mocks base method.
func (m *MockLLMService) CorrectSQL(ctx context.Context, prompt, invalidSQL, error string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CorrectSQL", ctx, prompt, invalidSQL, error)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CorrectSQL indicates an expected call of CorrectSQL.
func (mr *MockLLMServiceMockRecorder) CorrectSQL(ctx, prompt, invalidSQL, error interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CorrectSQL", reflect.TypeOf((*MockLLMService)(nil).CorrectSQL), ctx, prompt, invalidSQL, error)
}

// GenerateSQL mocks base method.
func (m *MockLLMService) GenerateSQL(ctx context.Context, prompt, context string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSQL", ctx, prompt, context)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSQL indicates an expected call of GenerateSQL.
func (mr *MockLLMServiceMockRecorder) GenerateSQL(ctx, prompt, context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSQL", reflect.TypeOf((*MockLLMService)(nil).GenerateSQL), ctx, prompt, context)
}
