// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/encrypt.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncryptRepository is a mock of EncryptRepository interface.
type MockEncryptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptRepositoryMockRecorder
}

// MockEncryptRepositoryMockRecorder is the mock recorder for MockEncryptRepository.
type MockEncryptRepositoryMockRecorder struct {
	mock *MockEncryptRepository
}

// NewMockEncryptRepository creates a new mock instance.
func NewMockEncryptRepository(ctrl *gomock.Controller) *MockEncryptRepository {
	mock := &MockEncryptRepository{ctrl: ctrl}
	mock.recorder = &MockEncryptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptRepository) EXPECT() *MockEncryptRepositoryMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptRepository) Decrypt(cipherText string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", cipherText)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptRepositoryMockRecorder) Decrypt(cipherText interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptRepository)(nil).Decrypt), cipherText)
}

// Encrypt mocks base method.
func (m *MockEncryptRepository) Encrypt(plainText string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plainText)
	ret0, _ := ret[0].(string)
	return ret0
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptRepositoryMockRecorder) Encrypt(plainText interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptRepository)(nil).Encrypt), plainText)
}
